class TgddPhoneItem():
    id = ""
    company = ""
    name = ""
    memory = ""
    color = ""
    originPrice = ""
    discountPrice = ""
    discountRate = ""
    screen = ""
    operatingSystem = ""
    frontCamera = ""
    behindCamera = ""
    chip = ""
    ram = ""
    sim = ""
    pin = ""
    imageUrl = ""
    